version: '3.7'

services:
  rabbit:
    build:
      context: ./docker
      dockerfile: rabbit.Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile